NKRO_ENABLE = yes # USB Nkey Rollover
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER =  WS2812
EXTRAKEY_ENABLE = yes
#TAP_DANCE_ENABLE = no
#BOOTMAGIC_ENABLE = no
UNICODEMAP_ENABLE = yes